export const REQUIRED_SETUP_TABLE_SUFFIXES = [
  "communication_attempts",
  "communication_messages",
  "system_settings",
  "data_domains",
  "domain_post_meta",
  "domain_posts",
  "media",
  "rbac_roles",
  "sessions",
  "site_data_domains",
  "sites",
  "site_user_table_registry",
  "term_relationships",
  "term_taxonomies",
  "term_taxonomy_domains",
  "term_taxonomy_meta",
  "terms",
  "users",
  "user_meta",
  "verificationTokens",
  "accounts",
  "webcallback_events",
  "webhook_subscriptions",
  "webhook_deliveries",
] as const;

export const OPTIONAL_LEGACY_SETUP_TABLE_SUFFIXES = [
  "categories",
  "examples",
  "post_categories",
  "post_meta",
  "post_tags",
  "posts",
  "tags",
] as const;

export const ALL_EXPECTED_SETUP_TABLE_SUFFIXES = [
  "accounts",
  "categories",
  "communication_attempts",
  "communication_messages",
  "system_settings",
  "data_domains",
  "domain_post_meta",
  "domain_posts",
  "examples",
  "media",
  "post_categories",
  "post_meta",
  "post_tags",
  "posts",
  "rbac_roles",
  "sessions",
  "site_data_domains",
  "sites",
  "site_user_table_registry",
  "tags",
  "term_relationships",
  "term_taxonomies",
  "term_taxonomy_domains",
  "term_taxonomy_meta",
  "terms",
  "users",
  "user_meta",
  "verificationTokens",
  "webcallback_events",
  "webhook_subscriptions",
  "webhook_deliveries",
] as const;
