export const REQUIRED_SETUP_TABLE_SUFFIXES = [
  "network_accounts",
  "network_communication_attempts",
  "network_communication_messages",
  "network_rbac_roles",
  "network_sessions",
  "network_sites",
  "network_system_settings",
  "network_user_meta",
  "network_users",
  "network_verification_tokens",
  "network_webcallback_events",
  "network_webhook_deliveries",
  "network_webhook_subscriptions",
] as const;

export const OPTIONAL_LEGACY_SETUP_TABLE_SUFFIXES = [
  "categories",
  "post_categories",
  "post_meta",
  "post_tags",
  "posts",
  "tags",
] as const;

export const ALL_EXPECTED_SETUP_TABLE_SUFFIXES = [
  "categories",
  "network_accounts",
  "network_communication_attempts",
  "network_communication_messages",
  "network_rbac_roles",
  "network_sessions",
  "network_sites",
  "network_system_settings",
  "network_user_meta",
  "network_users",
  "network_verification_tokens",
  "network_webcallback_events",
  "network_webhook_deliveries",
  "network_webhook_subscriptions",
  "post_categories",
  "post_meta",
  "post_tags",
  "posts",
  "tags",
] as const;
